version: "3.1"

#
# NOTE: Connect to a Cassandra node: 
#       docker run -it --network cass-net --rm cassandra cqlsh <container-name>
#

services:
    cassandra-1:
        image: cassandra:latest
        container_name: cassandra-1
        restart: always
        tty: true
        volumes:
            - $PWD/data/node1:/var/lib/cassandra/data
        networks:
            - cass-net
        environment:
            CASSANDRA_START_RPC:       "true"
            CASSANDRA_CLUSTER_NAME:    MyCluster
            CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
            CASSANDRA_DC:              datacenter

    cassandra-2:
        image: cassandra:latest
        container_name: cassandra-2
        restart: always
        tty: true
        command: sh -c "sleep 30; /usr/local/bin/docker-entrypoint.sh cassandra -f"
        volumes:
            - $PWD/data/node2:/var/lib/cassandra/data
        depends_on:
            - "cassandra-1"
        networks:
            - cass-net
        environment:
            CASSANDRA_START_RPC:       "true"
            CASSANDRA_CLUSTER_NAME:    MyCluster
            CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
            CASSANDRA_DC:              datacenter
            CASSANDRA_SEEDS:           cassandra-1

    server:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: flask_app
        image: flask_app
        restart: always
        tty: true
        command: sh -c "sleep 60; python3 flask_app.py"
        ports:
            - "5000:5000"
        volumes:
            - ./:/app/
        environment:
            CASSANDRA_HOSTS: cassandra-1
            TEST_VAR: one,two,three
        depends_on:
            - "cassandra-1"
        networks:
            - cass-net
            
networks:
    cass-net:
        external: false


